import type { Metadata } from "next";
import { Kanit, Sarabun } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";
import "@/lib/fontawesome";
import { Toaster } from "sonner";

const fontHeader = Kanit({
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-kanit",
  subsets: ["thai", "latin"],
  display: "swap",
});

const fontBody = Sarabun({
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-sarabun",
  subsets: ["thai", "latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "ระบบติดตามโครงการตามแผนปฏิบัติการด้านการพัฒนาสังคมจังหวัดกำแพงเพชร",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="corporate">
      <body
        className={`${fontHeader.variable} ${fontBody.variable} font-sans antialiased`}
      >
        {children}
        <Toaster position="top-right" />
        <Analytics />
      </body>
    </html>
  );
}
